title: Camila Duitama Portfolio
description: Python‑focused software engineer with advanced expertise in backend development, data engineering, and algorithmic solutions.

baseurl: "/portfolio-html"
url: "https://camiladuitama.github.io"

# Ensure these are set
source: .
destination: ./_site

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown

# Defaults to ensure layout is applied
defaults:
  - scope:
      path: ""
    values:
      layout: default