title: Camila Duitama Portfolio
description: Personal Portfolio Website
theme: jekyll-theme-minimal

# Ensure these are set correctly
source: .
destination: ./_site

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown