title: Camila Duitama Portfolio
description: Personal Portfolio Website

# Ensure these are set
source: .
destination: ./_site

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown

# Defaults to ensure layout is applied
defaults:
  - scope:
      path: ""
    values:
      layout: default