title: Camila Duitama Portfolio
description: Personal Portfolio Website
theme: jekyll-theme-minimal

# Explicitly set source and destination
source: ./docs
destination: ./docs/_site

# Specify index file
index_file: index.md

# Additional configurations
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown